### PR TITLE
Component Identifiers and BOM/Placement for jlcpcb

### PR DESCRIPTION
**Pull request by MrBatschner**
Hi,

to extend the life of my trusty Model Ms for another half century, I just tried to order a batch of PCBs for your USB controller from JLCPCB and made use of their SMT population/soldering service (as recently mentioned on Heise online).

So I looked up all of their part-numbers for SMD components (LCSC numbers) and added them the V1 .sch file and also created the BOM and placement files for manufacturing. Just thought to contribute these files to the project in case anybody else wanted to order ready-made PCBs (SMD soldering is not for everyone) through their service.

Cheers and thank you for making this project openly available!

### CODE REVIEW

**Review by mschwingen — APPROVED** [review]
Thanks - please report back how it turned out!

**Comment by MrBatschner** [comment]
Reporting back on how the boards turned out.

They (jclpcb) delivered a really good job with all the components where they should be and with the correct orientation. In fact, I am currently typing these lines on a Model M with one of these boards and your QMK firmware in it.

Things to note with the files in this PR: 
- I got V1 produced and my files are for V1 (should have taken V2, I know...)
- my bom/placement files populate the MAX reset generator as well as the R/C for reset generation, so I had to desolder R6 and C13
- I initially did not see the "dnp" annotation for R1 and R5 so I had to desolder those as well
- the LED resistors are populated with 0 Ohms as the two Model Ms I took apart prior to ordering do have the resistors on the LED board
- biggest issue: there seem to be Model Ms with no dedicated cable for the LEDs and three out of the five Model Ms I own are of that type (manufactured in 1994, German layout and yes, those are the ones I did not open beforehand). The four wires for the LEDs are part of the column ribbon and consequently, the ribbon/ffc connector on the board has 12 pins, not eight. So out of the box, your drop-in replacement board is not suitable for these Model Ms... however, nothing that cannot be fixed with some jumper wires. These LEDs will require the 120Ohm resistors.
Maybe I will take your design and modify it to accommodate these Model Ms as well...

**Comment by nuess0r** [comment]
Hi

Just saw your discussion here because I'm also working on another QMK for Model M controller (after I did a TMK port to the old dulcimer controller).

The Yugo-M project is addressing the variants with 8 and 12 pin ribbon connectors as well. In the meantime (also with the of Brandon from Clickykeyboards) I learned that there are even more LED connector position variants. I also address the the small/big PCB variants. In my controller you can break away what you don't need.

Today I polished my KiCAD project a bit more and did a first push, so you can have a look at it:
https://github.com/nuess0r/ctrl-M

I'm happy about the project of @mschwingen as he developted the 3D printing models to cover the back. This will be useful for me as well. And we share most design decisions :-)

**Comment by mschwingen** [comment]
On 24.03.21 18:11, Thomas Buchner wrote:
>
> Reporting back on how the boards turned out.
>
> They (jclpcb) delivered a really good job with all the components
> where they should be and with the correct orientation. In fact, I am
> currently typing these lines on a Model M with one of these boards and
> your QMK firmware in it.
>
Great!
>
> Things to note with the files in this PR:
>
>   * I got V1 produced and my files are for V1 (should have taken V2, I
>     know...)
>   * my bom/placement files populate the MAX reset generator as well as
>     the R/C for reset generation, so I had to desolder R6 and C13
>   * I initially did not see the "dnp" annotation for R1 and R5 so I
>     had to desolder those as well
>
Yes, I tend to add just-in-case parts in my designs when details are not
yet sure - sometimes, it saves another prototype run, but you have to
take care to leave out the dnp parts.
>
>   * the LED resistors are populated with 0 Ohms as the two Model Ms I
>     took apart prior to ordering do have the resistors on the LED board
>
Well - there is no solution that fits everyone, due to the variations in
the Model M hardware. I will add your comments to the readme.
>
>   * biggest issue: there seem to be Model Ms with no dedicated cable
>     for the LEDs and three out of the five Model Ms I own are of that
>     type (manufactured in 1994, German layout and yes, those are the
>     ones I did not open beforehand). The four wires for the LEDs are
>     part of the column ribbon and consequently, the ribbon/ffc
>     connector on the board has 12 pins, not eight. So out of the box,
>     your drop-in replacement board is not suitable for these Model
>     Ms... however, nothing that cannot be fixed with some jumper
>     wires. These LEDs will require the 120Ohm resistors.
>     Maybe I will take your design and modify it to accommodate these
>     Model Ms as well...
>
Bummer. I never had one of these, and I did not find those variants when
gooling what other people have built.

I have 4 keyboards from 1989 - 1994 myself, and had a colleague look
though his collection too - beside PCB variations (size/circuit), these
are basically 3 different versions (two different LED boards, and one
where the PCB is directly bonded to the row/column flex cable without a
connector).

How does the other end of the LED connection look like on your model?

best regards,

Michael

**Comment by mschwingen** [comment]
On 24.03.21 21:54, nuess0r wrote:
>
> Hi
>
> Just saw your discussion here because I'm also working on another QMK
> for Model M controller (after I did a TMK port to the old dulcimer
> controller).
>
> The Yugo-M project is addressing the variants with 8 and 12 pin ribbon
> connectors as well. In the meantime (also with the of Brandon from
> Clickykeyboards) I learned that there are even more LED connector
> position variants. I also address the the small/big PCB variants. In
> my controller you can break away what you don't need.
>
> Today I polished my KiCAD project a bit more and did a first push, so
> you can have a look at it:
> https://github.com/nuess0r/ctrl-M <https://github.com/nuess0r/ctrl-M>
>
Looks good. I Wish I had known about the 12-column-flex versions before :-(

I had thought about using a STM32 for my design, but after some prior
experience with the ST USB stack, the USB software support on the Atmega
looked better.

Some notes:

- The LD1117 datasheet does not make any notes about stability. Similar
LDOs from other vendors (LM1117 etc.) are known to become unstable with
low-esr (ceramic) output capacitors, so I would guess the LD1117 to
behave similarly. C3 (0805 ceramic) may have a too-low ESR for stable
operation - a 10uF electrolytic or tantalum might be a better choice (or
a LDO that is specified for ceramic output caps - I have used XC6206P33
in other projects, but here are lots of alternatives in SOT-23 available).

- Pinout. If you shuffle the pins around a bit, you can connect the LEDs
to PWM-capable pins (eg. TIMER3/CH1-3 on PA6, PA7, PB0).

- why the STM32F072 and not the STM32F070?

cu

Michael

**Comment by nuess0r** [comment]
> I have used XC6206P33 in other projects, but here are lots of alternatives in SOT-23 available).

Good point. I'll have a look at this.

> - Pinout. If you shuffle the pins around a bit, you can connect the LEDs to PWM-capable pins (eg. TIMER3/CH1-3 on PA6, PA7, PB0).

Never cared about something like this. But when I can have it with low effort, why not. I'll take a look at it.

> -  why the STM32F072 and not the STM32F070

Because the F072 is the cheapest one that is mentioned as compatible with QMK and has enough I/Os to cover a Model M (If I remember correctly the F032 has too few I/Os , same issue as with the ATmega32u4)
https://docs.qmk.fm/#/compatible_microcontrollers?id=arm

**Comment by MrBatschner** [comment]
> Bummer. I never had one of these, and I did not find those variants when gooling what other people have built.

Well, I uploaded a proposal for a possible V3 with the 12-pin connector to my fork at https://github.com/MrBatschner/hardware/tree/master/modelm-usb/V3. It still lacks the proper part numbers but if you have no objections, I will open another PR for it once finished.

> How does the other end of the LED connection look like on your model? best regards, Michael

It looks like in your ffc picture. A small board with three LEDs and a four-pin ffc connector on it. 

In fact, you could cut he column ribbon in two and get the connections that your board is designed for (but that would come with two problems: as the ffc connectors are not easily available (especially if you are scared off by Digikeys shipping fees), I usually take them from the original controller and it would remove the way back.

**Comment by mschwingen** [comment]
On 26.03.21 11:44, Thomas Buchner wrote:
>
>     Bummer. I never had one of these, and I did not find those
>     variants when gooling what other people have built.
>
> Well, I uploaded a proposal for a possible V3 with the 12-pin
> connector to my fork at
> https://github.com/MrBatschner/hardware/tree/master/modelm-usb/V3
> <https://github.com/MrBatschner/hardware/tree/master/modelm-usb/V3>.
> It still lacks the proper part numbers but if you have no objections,
> I will open another PR for it once finished.
>
Looks good - go ahead with the PR when it is complete.
>
>     How does the other end of the LED connection look like on your
>     model? best regards, Michael
>
> It looks like in your ffc picture. A small board with three LEDs and a
> four-pin ffc connector on it.
>
> In fact, you could cut he column ribbon in two and get the connections
> that your board is designed for (but that would come with two
> problems: as the ffc connectors are not easily available (especially
> if you are scared off by Digikeys shipping fees), I usually take them
> from the original controller and it would remove the way back.
>
OK. I did that with my first prototype, but then I did an order with
Mouser to get the connectors and some other parts, so now I have enough
connectors to modify all my own and my friend's Model M ;-)

cu

Michael

**Comment by nuess0r** [comment]
>It still lacks the proper part numbers but if you have no objections, I will open another PR for it once finished.

> In fact, you could cut he column ribbon in two and get the connections that your board is designed for (but that would come with two problems: as the ffc connectors are not easily available (especially if you are scared off by Digikeys shipping fees), I usually take them from the original controller and it would remove the way back.

Interesting fact when you live in Europe: You can get them from Conrad. Kind of.

You have to know, that there is not only the Tyco Trio Mate connector (used on the original Model M) but there is an alternative the Connfly DS1020 which is on stock at Conrad. Also the price is interesting.

The Tyco Trio Mate I source in Europe from RS Components but they only do B2B.

**Pull request merged**
